---
title: "Setup-Script"
---

############### Make sure to run this script before running the Shiny application #######################

Packages
```{r packages}
# Install pacman
install_packages(pacman)
library(pacman)

# Install stopwords package
devtools::install_github("quanteda/stopwords")
list_of_stopwords <- stopwords::stopwords("da", source = "snowball") %>% c("ogsaa", "paa", "naar", "saadan")

# Install sentiment package, SENTIDA
if(!require("devtools")) install.packages("devtools")
devtools::install_github("Guscode/Sentida")
Sys.setlocale(category = "LC_ALL", locale = "UTF-8") # Make sure that sentida can work with æøå

# Install and load other necessary packages
pacman::p_load(shiny, 
               shinydashboard, 
               shinyjs, 
               stringr, 
               shinythemes,
               shinyBS,
               quanteda,
               tidyverse,
               ggforce,
               DT,
               LDAvis,
               topicmodels,
               tm, 
               dplyr,
               stm,
               readr,
               tidytext,
               Rtsne,
               SnowballC,
               plotly, 
               wordcloud, 
               visNetwork,
               bsplus,
               RColorBrewer, 
               readr, 
               colourpicker, 
               wordcloud2, 
               word2vec,
               fastTextR, 
               text2vec,
               ggplot2,
               shinycssloaders,
               highcharter,
               r2d3,
               Sentida,
               lemon,
               forcats,
               NLP,
               Cairo,
               ape,
               shinyWidgets,
               shinyalert)
```

Load the DAGW-model
```{r model}
DAGW_model <- read.word2vec(file = "DAGW-model.bin", normalize = TRUE)

# Files for practice tasks
file1 <- read.csv("www/Nytårstaler-korpus.csv", header = F, sep = ";")
file2 <- read.delim("www/1999.txt", header = F)
```

